In [109]:
import pandas as pd
df=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\IMDB TMDB Movie Metadata Big Dataset (1M).csv")

In [110]:
df.head(3)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,Star3,Star4,Writer,Director_of_Photography,Producers,Music_Composer,genres_list,Cast_list,overview_sentiment,all_combined_keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Elliot Page,Ken Watanabe,Christopher Nolan,Wally Pfister,"Thomas Tull, Christopher Nolan, Chris Brigham,...",Hans Zimmer,"['Action', 'Science Fiction', 'Adventure']","['Tim Kelleher', 'Silvie Laguna', 'Natasha Bea...",-0.011111,"['s', 'philosophy', 'skilled', 'kidnapping', '..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Jessica Chastain,Mackenzie Foy,Jonathan Nolan,Hoyte van Hoytema,"Jake Myers, Emma Thomas, Jordan Goldberg, Thom...",Hans Zimmer,"['Adventure', 'Drama', 'Science Fiction']","['Jeff Hephner', 'William Devane', 'Elyes Gabe...",0.045455,"['thoughtful', 'use', 'scientist', 'quantum me..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,Aaron Eckhart,Michael Caine,Jonathan Nolan,Wally Pfister,"Kevin De La Noy, Thomas Tull, Christopher Nola...","Hans Zimmer, James Newton Howard","['Drama', 'Action', 'Crime', 'Thriller']","['Tommy Lister Jr.', 'Edison Chen', 'Beatrice ...",0.025000,"['reign', 'harvey', 'proves', 'partnership', '..."

In [111]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'production_companies',
       'production_countries', 'spoken_languages', 'keywords', 'release_year',
       'Director', 'AverageRating', 'Poster_Link', 'Certificate',
       'IMDB_Rating', 'Meta_score', 'Star1', 'Star2', 'Star3', 'Star4',
       'Writer', 'Director_of_Photography', 'Producers', 'Music_Composer',
       'genres_list', 'Cast_list', 'overview_sentiment',
       'all_combined_keywords'],
      dtype='object')

In [112]:
len(df.columns)

42

In [113]:
df.drop(columns=['status','release_date','revenue','adult','budget','homepage','original_language','original_title','popularity','tagline','production_countries','spoken_languages','Certificate','Writer','Director_of_Photography','Music_Composer','Cast_list','overview_sentiment','all_combined_keywords'],inplace=True)

In [114]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'runtime', 'backdrop_path',
       'imdb_id', 'overview', 'poster_path', 'production_companies',
       'keywords', 'release_year', 'Director', 'AverageRating', 'Poster_Link',
       'IMDB_Rating', 'Meta_score', 'Star1', 'Star2', 'Star3', 'Star4',
       'Producers', 'genres_list'],
      dtype='object')

In [115]:
len(df.columns)

23

In [116]:
df.head(3)

,id,title,vote_average,vote_count,runtime,backdrop_path,imdb_id,overview,poster_path,production_companies,...,AverageRating,Poster_Link,IMDB_Rating,Meta_score,Star1,Star2,Star3,Star4,Producers,genres_list
0,27205,Inception,8.364,34495,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"Legendary Pictures, Syncopy, Warner Bros. Pict...",...,8.8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,8.8,74.0,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"Thomas Tull, Christopher Nolan, Chris Brigham,...","['Action', 'Science Fiction', 'Adventure']"
1,157336,Interstellar,8.417,32571,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,"Legendary Pictures, Syncopy, Lynda Obst Produc...",...,8.7,https://m.media-amazon.com/images/M/MV5BZjdkOT...,8.6,74.0,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,"Jake Myers, Emma Thomas, Jordan Goldberg, Thom...","['Adventure', 'Drama', 'Science Fiction']"
2,155,The Dark Knight,8.512,30619,152,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,tt0468569,Batman raises the stakes in his war on crime. ...,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,"DC Comics, Legendary Pictures, Syncopy, Isobel...",...,9.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,9.0,84.0,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"Kevin De La Noy, Thomas Tull, Christopher Nola...","['Drama', 'Action', 'Crime', 'Thriller']"

In [117]:
df.shape

(1072255, 23)

In [118]:
df.isnull().sum()

id                            0
title                         0
vote_average                  0
vote_count                    0
runtime                       0
backdrop_path            779429
imdb_id                  482891
overview                 202181
poster_path              317838
production_companies     575683
keywords                      0
release_year             150556
Director                      0
AverageRating           1060504
Poster_Link             1069485
IMDB_Rating             1041943
Meta_score              1069924
Star1                   1041942
Star2                   1069485
Star3                   1069485
Star4                   1069485
Producers                646947
genres_list                   0
dtype: int64

In [119]:
# runtime,vote_count,vote_average,AverageRating,IMDB_Rating, Meta_score

In [120]:
df = df[df["runtime"] >= 70]

In [121]:
df.shape

(403286, 23)

In [122]:
df.sort_values(by='runtime',axis=0,inplace=True,ascending=False)

In [123]:
df = df[df["runtime"] <= 250]

In [124]:
df.shape

(398152, 23)

In [125]:
df.head()

,id,title,vote_average,vote_count,runtime,backdrop_path,imdb_id,overview,poster_path,production_companies,...,AverageRating,Poster_Link,IMDB_Rating,Meta_score,Star1,Star2,Star3,Star4,Producers,genres_list
781416,583769,Collected Hardcore 5,0.0,0,250,NaN,NaN,Nice horny teens!,/2z0GSzgjh8pNLXsp1355R4PoHMa.jpg,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Unknown']
804267,293889,Berlioz: Les Troyens,0.0,0,250,NaN,tt0253844,Berlioz’s colossal masterpiece requires stupen...,/uqx22h1nfuvhGCY8vKqBri7O8EO.jpg,Deutsche Grammophon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Music', 'History']"
318826,82554,Eläkeläiset: Sekoilun Ytimessä 1993-2003,3.5,1,250,NaN,NaN,"Various Live Concerts, Videos, Karaoke and spe...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Music']
777596,555213,Nasty Anal Tryouts 2,0.0,0,250,/vzhq7cO3qykS60kmdk6YSNLUFao.jpg,tt2336387,"Mike Adriano, creator of the AVN Award-winning...",/mrzOew7oyzLKZ2R0YVCaUxWGBsO.jpg,Evil Angel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Unknown']
180054,365944,Fashionistas Safado: The Challenge,9.0,2,250,/5FuNOnzstQy74Fkefr82zH0wZOV.jpg,tt0892293,"This sequel shot in high-definition in Berlin,...",/24XEXjEpK2j2CnvXWHBsP6wOL0Q.jpg,Evil Angel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ram Gopal Varma, Chiranjeevi Pedamallu",['Unknown']

In [133]:
df = df[df["vote_count"] >= 1000]

In [134]:
df.shape

(3911, 23)

In [135]:
df.head(3)

,id,title,vote_average,vote_count,runtime,backdrop_path,imdb_id,overview,poster_path,production_companies,...,AverageRating,Poster_Link,IMDB_Rating,Meta_score,Star1,Star2,Star3,Star4,Producers,genres_list
328,791373,Zack Snyder's Justice League,8.190,9202,242,/4LO6bnNGIa8zNbM6HwCYzlUKIHq.jpg,tt12361974,Determined to ensure Superman's ultimate sacri...,/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg,"Warner Bros. Pictures, The Stone Quarry, Atlas...",...,7.1,NaN,8.3,NaN,Mel Gibson,NaN,NaN,NaN,"Atom Magadia, Ferdinand Lapuz, Marco D. Bieman...","['Action', 'Adventure', 'Fantasy']"
1193,770,Gone with the Wind,7.965,3691,238,/ft8WRF2xqEwwGWa59naDUybKTAx.jpg,tt0031381,The spoiled daughter of a Georgia plantation o...,/lNz2Ow0wGCAvzckW7EOjE03KcYv.jpg,"Selznick International Pictures, Metro-Goldwyn...",...,NaN,https://m.media-amazon.com/images/M/MV5BYjUyZW...,8.1,97.0,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,"Jeffrey Silver, Yoshinobu Noma, Mark Sourian, ...","['Drama', 'War', 'Romance']"
864,311,Once Upon a Time in America,8.427,4863,229,/uPYa165sraN2c8gZBM9C47g3JoU.jpg,tt0087843,A former Prohibition-era Jewish gangster retur...,/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg,"The Ladd Company, Embassy International Pictur...",...,6.8,https://m.media-amazon.com/images/M/MV5BMGFkNW...,8.4,NaN,Robert De Niro,James Woods,Elizabeth McGovern,Treat Williams,NaN,"['Drama', 'Crime']"

In [136]:
df.isnull().sum()

id                         0
title                      0
vote_average               0
vote_count                 0
runtime                    0
backdrop_path              0
imdb_id                    0
overview                   0
poster_path                0
production_companies       4
keywords                   0
release_year               0
Director                   0
AverageRating           1050
Poster_Link             3300
IMDB_Rating              817
Meta_score              3315
Star1                    817
Star2                   3300
Star3                   3300
Star4                   3300
Producers               1638
genres_list                0
dtype: int64

In [137]:
df.dropna(subset=["poster_path"],inplace=True)

In [138]:
df.shape

(3911, 23)

In [140]:
import pandas as pd
import re

def combine_features(df, feature_weights, new_col_name='combined_features', sep=' '):
  
    df = df.copy()

    missing = [f for f in feature_weights if f not in df.columns]
    if missing:
        raise ValueError(f"These columns are not in the dataframe: {missing}")

    def tokenize(value):
        if pd.isna(value):
            return []
        value = str(value)
        tokens = re.split(r'[^a-zA-Z]+', value.strip())
        return [t.strip() for t in tokens if t.strip() != '']

    def process_row(row):
        words = []
        for feature, weight in feature_weights.items():
            tokens = tokenize(row[feature])
            words.extend(tokens * weight)  # repeat tokens `weight` times
        return sep.join(words)

    df[new_col_name] = df.apply(process_row, axis=1)
    return df

In [142]:
feature_weights = {
    'genres_list': 3,
    'keywords': 3,
    'Director': 3,
    'Star1': 2,
    'Star2': 2,
    'Star3': 2,
    'Star4': 2,
    'Producers': 1,
    'production_companies': 1,
    'overview': 1
}

df = combine_features(df, feature_weights, new_col_name='tags')
df.head(3)

,id,title,vote_average,vote_count,runtime,backdrop_path,imdb_id,overview,poster_path,production_companies,...,Poster_Link,IMDB_Rating,Meta_score,Star1,Star2,Star3,Star4,Producers,genres_list,tags
328,791373,Zack Snyder's Justice League,8.190,9202,242,/4LO6bnNGIa8zNbM6HwCYzlUKIHq.jpg,tt12361974,Determined to ensure Superman's ultimate sacri...,/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg,"Warner Bros. Pictures, The Stone Quarry, Atlas...",...,NaN,8.3,NaN,Mel Gibson,NaN,NaN,NaN,"Atom Magadia, Ferdinand Lapuz, Marco D. Bieman...","['Action', 'Adventure', 'Fantasy']",Action Adventure Fantasy Action Adventure Fant...
1193,770,Gone with the Wind,7.965,3691,238,/ft8WRF2xqEwwGWa59naDUybKTAx.jpg,tt0031381,The spoiled daughter of a Georgia plantation o...,/lNz2Ow0wGCAvzckW7EOjE03KcYv.jpg,"Selznick International Pictures, Metro-Goldwyn...",...,https://m.media-amazon.com/images/M/MV5BYjUyZW...,8.1,97.0,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,"Jeffrey Silver, Yoshinobu Noma, Mark Sourian, ...","['Drama', 'War', 'Romance']",Drama War Romance Drama War Romance Drama War ...
864,311,Once Upon a Time in America,8.427,4863,229,/uPYa165sraN2c8gZBM9C47g3JoU.jpg,tt0087843,A former Prohibition-era Jewish gangster retur...,/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg,"The Ladd Company, Embassy International Pictur...",...,https://m.media-amazon.com/images/M/MV5BMGFkNW...,8.4,NaN,Robert De Niro,James Woods,Elizabeth McGovern,Treat Williams,NaN,"['Drama', 'Crime']",Drama Crime Drama Crime Drama Crime new york c...

In [143]:
df.drop(columns=[
    'genres_list',
    'keywords',
    'Director',
    'Star1',
    'Star2',
    'Star3',
    'Star4',
    'Producers',
    'production_companies','overview'
],inplace=True)

In [144]:
len(df.columns)

14

In [146]:
df.drop(columns=['Poster_Link','Meta_score','AverageRating'],inplace=True)

In [147]:
df.head()

,id,title,vote_average,vote_count,runtime,backdrop_path,imdb_id,poster_path,release_year,IMDB_Rating,tags
328,791373,Zack Snyder's Justice League,8.190,9202,242,/4LO6bnNGIa8zNbM6HwCYzlUKIHq.jpg,tt12361974,/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg,2021.0,8.3,Action Adventure Fantasy Action Adventure Fant...
1193,770,Gone with the Wind,7.965,3691,238,/ft8WRF2xqEwwGWa59naDUybKTAx.jpg,tt0031381,/lNz2Ow0wGCAvzckW7EOjE03KcYv.jpg,1939.0,8.1,Drama War Romance Drama War Romance Drama War ...
864,311,Once Upon a Time in America,8.427,4863,229,/uPYa165sraN2c8gZBM9C47g3JoU.jpg,tt0087843,/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg,1984.0,8.4,Drama Crime Drama Crime Drama Crime new york c...
1663,947,Lawrence of Arabia,7.976,2689,228,/mx2jS5Kaa5rmaldEFzKeKpDN9Q2.jpg,tt0056172,/AiAm0EtDvyGqNpVoieRw4u65vD1.jpg,1962.0,8.3,Adventure Drama History War Adventure Drama Hi...
1800,665,Ben-Hur,7.870,2465,222,/sU3gFo7Gn67zjtKXIvzJ4omcUbH.jpg,tt0052618,/m4WQ1dBIrEIHZNCoAjdpxwSKWyH.jpg,1959.0,8.1,Action Drama History Adventure Action Drama Hi...

In [148]:
df.isnull().sum()

id                 0
title              0
vote_average       0
vote_count         0
runtime            0
backdrop_path      0
imdb_id            0
poster_path        0
release_year       0
IMDB_Rating      817
tags               0
dtype: int64

In [149]:
df.shape

(3911, 11)

In [150]:
df.to_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Final_Dataset_2.csv")